<?php

// Define the block that displays the module
function doi_display_block_info() {
  $blocks['doi_display'] = array(
    'info' => t('DOI Display'),
  );
  return $blocks;
}

// Define what is displayed in the module
function doi_display_block_view($delta='') {
  switch ($delta) {
  case 'doi_display':
      $doi = doi_display_get_content();
      $block['subject'] = t("Citation");
      $block['content'] = $doi;
      return $block;
      break;
  }
}

// The subroutine that creates the actual display
// 29 = 9 + length of identifier (including doi:)
function doi_display_get_content() {
    
    $doi = "doi:10.5065/D6DR2SJP";
    $url = "http://ezid.cdlib.org/manage/display_xml/";
    $full_url = $url . $doi;   

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $full_url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $xml = curl_exec($ch);
    curl_close($ch);


// Separate the xml in $output into objects that PHP can grab
    $xmlobj = simplexml_load_string($xml);
 
// Create variables for each of the metadata items
    $identifier = $xmlobj->identifier;
    $creator = $xmlobj->creators->creator->creatorName;
    $title = $xmlobj->titles->title;
    $publisher = $xmlobj->publisher;
    $description = $xmlobj->descriptions->description;
    $contributors = $xmlobj->contributors;
    $dates = $xmlobj->dates->date;
    $rights = $xmlobj->rightsList->rights;
    $location = $xmlobj->geoLocations->geoLocation->geoLocationPlace;
 

// Pull the full citation from the doi.org webiste
    $url = "http://doi.org/10.5065/D6DR2SJP";
    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
    $citation_style = "american-geophysical-union";
    $headers = array("Accept: text/x-bibliography; style=" . $citation_style);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    $citation = curl_exec($ch);
    curl_close($ch);

// Create the citation text that will be displayed in the block
    $output = ("When referencing the " . $title . " in publications or proposals, please use the identifier <strong>" . $doi . "</strong> -- for example as a citation:<br><blockquote> " . $citation . "<br> <a style='color:#297AC9' href='http://dx.doi.org/". $identifier . "'> http://dx.doi.org/" . $identifier . "</a></blockquote> or as a footnote:<blockquote> " . $creator . ", " . $title . ", <br> <a style='color:#297AC9' href='http://dx.doi.org/" . $identifier . "'> http://dx.doi.org/" . $identifier . "</a></blockquote> Please be careful of linebreaks when cutting and pasting the above text, and feel free to reformat to fit your document. Additional citation styles are avilable at <a style='color:#297AC9' href='http://data.datacite.org/" . $identifier . "'>DataCite</a> or <a style='color:#297AC9' href='http://crosscite.org/citeproc/'>CrossCite</a>.");

    return $output;
}
