<?php

// Define the block that displays the module
function doi_display_block_info() {
  $blocks['doi_display'] = array(
    'info' => t('DOI Display'),
  );
  return $blocks;
}

// Define what is displayed in the module
function doi_display_block_view($delta='') {
  switch ($delta) {
  case 'doi_display':
      $doi = doi_display_get_content();
      $block['subject'] = t("Citation");
      $block['content'] = $doi;
      return $block;
      break;
  }
}

// The subroutine that creates the actual display
function doi_display_get_content() {
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, 'http://ezid.cdlib.org/id/doi:10.5065/D6DR2SJP');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $output = curl_exec($ch);
    return $output;
}
